<form class="log-in-form"
action="<?=App::config('url')?>login/authorize"
method="POST">
  <h4 class="text-center">Authorization</h4>
  <label>Email
    <input type="email" name="email" placeholder="marija@edunova.hr"
    value="<?=$email?>" />
  </label>
  <label>Password
    <input type="password" name="password" />
  </label>
  <p>
    <input type="submit" class="button expanded" value="Login" />
  </p>
  <?=$message?>
</form>


