<form action="<?=App::config('url')?>razvijac/dodajNovi" method="post">

    <fieldset>
        <legend>Dodavanje novog razvijača</legend>


        <label>
            Naziv
            <input type="text" name="naziv" value="<?=$razvijac->naziv?>" />
        </label>

        <label>
            Država
            <input type="text" name="drzava" value="<?=$razvijac->drzava?>" />
        </label>

        <label>
            Webstranica
            <input type="text" name="webstranica" value="<?=$razvijac->webstranica?>" />
        </label>

        

        <div class="grid-x grid-padding-x">
            <div class="large-4 cell">
                <a  class="alert button expanded" 
                href="<?=App::config('url')?>razvijac/index">Odustani</a>
            </div>
            <div class="large-8 cell">
                <input type="submit" class="success button expanded" value="Dodaj novi">
            </div>
        </div>
        <?=$poruka?>

    </fieldset>
</form>