<form action="<?=App::config('url')?>razvijac/promjeni" method="post">

    <fieldset>
        <legend>Promjena postojećeg razvijača</legend>


        <label>
            Naziv
            <input type="text" name="naziv" value="<?=$razvijac->naziv?>" />
        </label>

        <label>
            Država
            <input type="text" name="drzava" value="<?=$razvijac->drzava?>" />
        </label>

        <label>
            Webstranica
            <input type="text" name="webstranica" value="<?=$razvijac->webstranica?>" />
        </label>

        <input type="hidden" name="sifra" value="<?=$razvijac->sifra?>">

        <div class="grid-x grid-padding-x">
            <div class="large-4 cell">
                <a  class="alert button expanded" 
                href="<?=App::config('url')?>razvijac/index">Odustani</a>
            </div>
            <div class="large-8 cell">
                <input type="submit" class="success button expanded" value="Promjeni">
            </div>
        </div>
        <?=$poruka?>

    </fieldset>
</form>