<div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle></button>
  <div class="title-bar-title"><?=App::config('naslovApp')?></div>
</div>

<div class="top-bar" id="example-menu">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text"><?=App::config('naslovApp')?></li>
      <li><a href="<?=App::config('url')?>">Početna</a></li>
      <?php if(App::autoriziran()):?>
        <li><a href="<?=App::config('url')?>nadzornaploca/index">Nadzorna ploča</a></li>
      <?php endif;?>
      <li class="has-submenu">
        <a href="#0">Vježbanje</a>
        <ul class="submenu menu vertical" data-submenu>
          <li><a href="<?=App::config('url')?>vjezba/primjer1">Primjer 1</a></li>
          <li><a href="<?=App::config('url')?>vjezba/primjer2">Primjer 2</a></li>
          <li><a href="<?=App::config('url')?>vjezba/primjer3">Primjer 3</a></li>
          <li><a href="<?=App::config('url')?>vjezba/primjer3lose">Primjer 3 LOŠE</a></li>
          <li><a href="<?=App::config('url')?>javascript/index">Osnove Javascript-e</a></li>
          <li><a href="<?=App::config('url')?>javascript/jquery">Osnove JQuery-a</a></li>
        </ul>
      </li>
      <?php if(App::autoriziran()):?>
        <li><a href="#">Programi</a>
          <ul class="submenu menu vertical" data-submenu>
            <li><a href="<?=App::config('url')?>izdavac/index">Izdavaci</a></li>
            <li><a href="<?=App::config('url')?>razvijac/index">Razvijaci</a></li>
            <li><a href="<?=App::config('url')?>igra/index">Igre</a></li>
            <li><a href="<?=App::config('url')?>korisnik/index">Korisnik</a></li>
            <li><a href="<?=App::config('url')?>narudzba/index">Narudzbe</a></li>
            <?php if(App::admin()):?>
              <li><a href="<?=App::config('url')?>operater/index">Operateri</a></li>
            <?php endif;?>
          </ul>
        </li>
      <?php endif;?>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <li>
        <?php if(App::autoriziran()):?>
          <a href="<?=App::config('url')?>login/odjava">Odjavi <?php echo $_SESSION['autoriziran']->ime ?></a>
        <?php else:?>
          <a href="<?=App::config('url')?>login/index">Login</a>
        <?php endif;?>
      </li>
    </ul>
  </div>
</div>