<form action="<?=App::config('url')?>korisnik/akcija" method="post">

    <fieldset>
        <legend>Detalji igara</legend>


        <label>
            Ime
            <input type="text" name="ime" value="<?=$korisnik->ime?>" />
        </label>

        <label>
            Prezime
            <input type="text" name="prezime" value="<?=$korisnik->prezime?>" />
        </label>

        <label>
            Korisničko ime
            <input type="text" name="korisnicko" value="<?=$korisnik->korisnicko?>" />
        </label>

        <label>
            OIB
            <input type="text" name="oib" value="<?=$korisnik->oib?>" />
        </label>

        <label>
            Email
            <input type="email" name="email" value="<?=$korisnik->email?>" />
        </label>


        <input type="hidden" name="sifra" value="<?=$korisnik->sifra?>">

        <div class="grid-x grid-padding-x">
            <div class="large-4 cell">
                <a  class="alert button expanded" 
                href="<?=App::config('url')?>korisnik/index">Odustani</a>
            </div>
            <div class="large-8 cell">
                <input type="submit" class="success button expanded" value="<?=$akcija?>">
            </div>
        </div>
        <?=$poruka?>

    </fieldset>
</form>