<div class="grid-x">
    <div class="cell large-6">
        <h1 style="font-size: 1.5rem;">Users</h1>
    </div>
    <div class="cell large-6" style="text-align: right">
        <a href="<?= App::config('url') ?>users/new">
            <i style="color:green;" title="Add new" class="fas fa-2x fa-plus-circle"></i>
        </a>
    </div>
</div>
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Surname</th>
            <th>Username</th>
            <th>Password</th>
            <th>Gender</th>
            <th>Age</th>
            <th>Email</th>
            <th>Country</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($users as $users) : ?>
            <tr>
                <td><?= $users->name ?></td>
                <td><?= $users->surname ?></td>
                <td><?= $users->username ?></td>
                <td><?= $users->password ?></td>
                <td><?= $users->gender ?></td>
                <td><?= $users->age ?></td>
                <td><?= $users->email ?></td>
                <td><?= $users->country ?></td>
                <td>
                    <a href="<?= App::config('url') ?>users/change?id=<? $users->id ?>">
                        <i title="Change &quot;<?= $users->name ?>&quot;" class="fas fa-2x fa-edit"></i>
                    </a>
                    <?php if ($users->wishlists === 0) : ?>
                        <a onclick="return confirm('Are you sure you want to delete <?= $users->name ?>?');" style="margin-left: 20px;" href="<?= App::config('url') ?>users/delete/<?=$users->id?>">
                            <i style="color: red" title="Delete <?= $users->name ?>" class="fas fa-2x fa-trash"></i>
                        </a>
                    <?php else : ?>
                        <i style="margin-left: 20px;color: gray" title="Cannot delete  <?= $users->name ?> because there are games" class="fas fa-2x fa-trash"></i>
                    <?php endif; ?>

                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>