<div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle></button>
  <div class="title-bar-title"><?=App::config('titleApp')?></div>
</div>

<div class="top-bar" id="example-menu">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text"><?=App::config('titleApp')?></li>
      <li><a href="<?=App::config('url')?>">Front Page</a></li>
      <li class="has-submenu">
        <a href="#0">Practice</a>
        <ul class="submenu menu vertical" data-submenu>
          <li><a href="<?=App::config('url')?>practice/example1">Example 1</a></li>
          <li><a href="<?=App::config('url')?>practice/example2">Example 2</a></li>
          <li><a href="<?=App::config('url')?>practice/example3">Example 3</a></li>
        </ul>
      </li>
      <li><a href="#0">Three</a></li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <li><input type="search" placeholder="Search"></li>
      <li><button type="button" class="button">Search</button></li>
    </ul>
  </div>
</div>