<div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle></button>
  <div class="title-bar-title"><?=App::config('titleApp')?></div>
</div>

<div class="top-bar" id="example-menu">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text"><?=App::config('titleApp')?></li>
      <li><a href="<?=App::config('url')?>">Front Page</a></li>
      <?php if(App::authorized()):?>
        <li><a href="<?=App::config('url')?>dashboard/index">Dashboard</a></li>
      <?php endif;?>
      <li class="has-submenu">
        <a href="#0">Practice</a>
        <ul class="submenu menu vertical" data-submenu>
          <li><a href="<?=App::config('url')?>practice/example1">Example 1</a></li>
          <li><a href="<?=App::config('url')?>practice/example2">Example 2</a></li>
          <li><a href="<?=App::config('url')?>practice/example3">Example 3</a></li>
        </ul>
      </li>
      <?php if(App::authorized()):?>
      <li><a href="#">Programs</a>
      <ul class="submenu menu vertical" data-submenu>
          <li><a href="<?=App::config('url')?>publishers/index">Publishers</a></li>
          <li><a href="<?=App::config('url')?>developers/index">Developers</a></li>
          <li><a href="<?=App::config('url')?>users/index">Users</a></li>
          <li><a href="<?=App::config('url')?>games/index">Games</a></li>
          <li><a href="<?=App::config('url')?>orders/index">Orders</a></li>
          <li><a href="<?=App::config('url')?>wishlists/index">Wishlists</a></li>
        </ul>
      </li>
      <?php endif;?>
    </ul>
  </div>
  <div class="top-bar-right">
  <ul class="menu">
      <li>
        <?php if(App::authorized()):?>
          <a href="<?=App::config('url')?>login/logout">Logout <?php echo $_SESSION['authorized']->name ?></a>
        <?php else:?>
          <a href="<?=App::config('url')?>login/index">Login</a>
        <?php endif;?>
      </li>
    </ul>
  </div>
</div>