<div class="grid-x">
    <div class="cell large-6">
        <h1 style="font-size: 1.5rem;">Developers</h1>
    </div>
    <div class="cell large-6" style="text-align: right">
        <a href="<?= App::config('url') ?>developers/new">
            <i style="color:green;" title="Add new" class="fas fa-2x fa-plus-circle"></i>
        </a>
    </div>
</div>
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Country</th>
            <th>Website</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($developers as $developers) : ?>
            <tr>
                <td><?= $developers->name ?></td>
                <td><?= $developers->country ?></td>
                <td><?= $developers->website ?></td>
                <td>
                    <a href="<?= App::config('url') ?>developers/change?id=<? $developers->id ?>">
                        <i title="Change &quot;<?= $developers->name ?>&quot;" class="fas fa-2x fa-edit"></i>
                    </a>
                    <?php if ($developers->games === 0) : ?>
                        <a onclick="return confirm('Are you sure you want to delete <?= $developers->name ?>?');" style="margin-left: 20px;" href="<?= App::config('url') ?>developers/delete/<?=$developers->id?>">
                            <i style="color: red" title="Delete <?= $developers->name ?>" class="fas fa-2x fa-trash"></i>
                        </a>
                    <?php else : ?>
                        <i style="margin-left: 20px;color: gray" title="Cannot delete  <?= $developers->name ?> because there are games" class="fas fa-2x fa-trash"></i>
                    <?php endif; ?>

                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>